/**
 * SDK Builder
 * Auto-generates client SDKs in multiple languages for each published API
 */

import { config } from '../config/index.js';
import db from '../utils/database.js';

/**
 * Generate SDK for an API in the specified language
 */
export function generateSDK(apiSlug, language = 'javascript') {
  const api = db.prepare(`
    SELECT * FROM apis WHERE slug = ? AND status = 'active'
  `).get(apiSlug);

  if (!api) throw new Error('API not found');

  const schema = JSON.parse(api.schema_definition);
  const baseUrl = `${config.baseUrl}/api/v1/live/${api.slug}`;

  const generators = {
    javascript: generateJavaScriptSDK,
    python: generatePythonSDK,
    curl: generateCurlExamples,
    typescript: generateTypeScriptSDK,
  };

  const generator = generators[language];
  if (!generator) throw new Error(`Unsupported language: ${language}. Supported: ${Object.keys(generators).join(', ')}`);

  return {
    language,
    apiName: api.name,
    apiSlug: api.slug,
    code: generator(api, schema, baseUrl),
    installInstructions: getInstallInstructions(language, api),
  };
}

/**
 * Generate JavaScript/Node.js SDK
 */
function generateJavaScriptSDK(api, schema, baseUrl) {
  const className = toPascalCase(api.name) + 'Client';
  const resources = schema.resources || [];

  let code = `/**
 * ${api.name} SDK - Auto-generated by APIForge
 * Documentation: ${config.seo.siteUrl}/api/${api.slug}/docs
 * Version: ${api.version || '1.0.0'}
 */

class ${className} {
  constructor(apiKey, options = {}) {
    this.apiKey = apiKey;
    this.baseUrl = options.baseUrl || '${baseUrl}';
    this.timeout = options.timeout || 30000;
  }

  async _request(method, path, data = null, params = {}) {
    const url = new URL(\`\${this.baseUrl}\${path}\`);
    Object.entries(params).forEach(([k, v]) => {
      if (v !== undefined && v !== null) url.searchParams.set(k, v);
    });

    const options = {
      method,
      headers: {
        'X-API-Key': this.apiKey,
        'Content-Type': 'application/json',
        'User-Agent': '${className}/1.0',
      },
      ...(data && { body: JSON.stringify(data) }),
    };

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), this.timeout);
    options.signal = controller.signal;

    try {
      const response = await fetch(url.toString(), options);
      clearTimeout(timeout);

      if (!response.ok) {
        const error = await response.json().catch(() => ({}));
        throw new APIForgeError(response.status, error.message || 'Request failed', error);
      }

      return response.json();
    } catch (err) {
      clearTimeout(timeout);
      if (err.name === 'AbortError') throw new APIForgeError(408, 'Request timeout');
      throw err;
    }
  }

`;

  // Generate methods for each resource
  resources.forEach(resource => {
    const name = resource.name.toLowerCase();
    const plural = name.endsWith('s') ? name : `${name}s`;
    const methods = resource.methods || ['GET', 'POST', 'PUT', 'DELETE'];

    if (methods.includes('GET')) {
      code += `  /** List all ${plural} */
  async list${toPascalCase(plural)}(params = {}) {
    return this._request('GET', '/${plural}', null, params);
  }

  /** Get a single ${name} by ID */
  async get${toPascalCase(name)}(id) {
    return this._request('GET', \`/${plural}/\${id}\`);
  }

`;
    }

    if (methods.includes('POST')) {
      code += `  /** Create a new ${name} */
  async create${toPascalCase(name)}(data) {
    return this._request('POST', '/${plural}', data);
  }

`;
    }

    if (methods.includes('PUT')) {
      code += `  /** Update a ${name} */
  async update${toPascalCase(name)}(id, data) {
    return this._request('PUT', \`/${plural}/\${id}\`, data);
  }

`;
    }

    if (methods.includes('DELETE')) {
      code += `  /** Delete a ${name} */
  async delete${toPascalCase(name)}(id) {
    return this._request('DELETE', \`/${plural}/\${id}\`);
  }

`;
    }
  });

  code += `}

class APIForgeError extends Error {
  constructor(status, message, details = {}) {
    super(message);
    this.name = 'APIForgeError';
    this.status = status;
    this.details = details;
  }
}

export default ${className};
export { ${className}, APIForgeError };
`;

  return code;
}


/**
 * Generate Python SDK
 */
function generatePythonSDK(api, schema, baseUrl) {
  const className = toPascalCase(api.name) + 'Client';
  const resources = schema.resources || [];

  let code = `"""
${api.name} SDK - Auto-generated by APIForge
Documentation: ${config.seo.siteUrl}/api/${api.slug}/docs
Version: ${api.version || '1.0.0'}
"""

import requests
from typing import Optional, Dict, Any


class APIForgeError(Exception):
    def __init__(self, status: int, message: str, details: dict = None):
        self.status = status
        self.message = message
        self.details = details or {}
        super().__init__(f"[{status}] {message}")


class ${className}:
    def __init__(self, api_key: str, base_url: str = "${baseUrl}", timeout: int = 30):
        self.api_key = api_key
        self.base_url = base_url
        self.timeout = timeout
        self.session = requests.Session()
        self.session.headers.update({
            "X-API-Key": api_key,
            "Content-Type": "application/json",
            "User-Agent": "${className}/1.0",
        })

    def _request(self, method: str, path: str, data: dict = None, params: dict = None) -> dict:
        url = f"{self.base_url}{path}"
        response = self.session.request(
            method=method,
            url=url,
            json=data,
            params=params,
            timeout=self.timeout,
        )
        if not response.ok:
            error = response.json() if response.text else {}
            raise APIForgeError(response.status_code, error.get("message", "Request failed"), error)
        return response.json()

`;

  resources.forEach(resource => {
    const name = resource.name.toLowerCase();
    const plural = name.endsWith('s') ? name : `${name}s`;
    const methods = resource.methods || ['GET', 'POST', 'PUT', 'DELETE'];

    if (methods.includes('GET')) {
      code += `    def list_${plural}(self, page: int = 1, limit: int = 20, **kwargs) -> dict:
        """List all ${plural}"""
        return self._request("GET", "/${plural}", params={"page": page, "limit": limit, **kwargs})

    def get_${name}(self, id: str) -> dict:
        """Get a single ${name} by ID"""
        return self._request("GET", f"/${plural}/{id}")

`;
    }

    if (methods.includes('POST')) {
      code += `    def create_${name}(self, data: dict) -> dict:
        """Create a new ${name}"""
        return self._request("POST", "/${plural}", data=data)

`;
    }

    if (methods.includes('PUT')) {
      code += `    def update_${name}(self, id: str, data: dict) -> dict:
        """Update a ${name}"""
        return self._request("PUT", f"/${plural}/{id}", data=data)

`;
    }

    if (methods.includes('DELETE')) {
      code += `    def delete_${name}(self, id: str) -> dict:
        """Delete a ${name}"""
        return self._request("DELETE", f"/${plural}/{id}")

`;
    }
  });

  return code;
}

/**
 * Generate TypeScript SDK (with full types)
 */
function generateTypeScriptSDK(api, schema, baseUrl) {
  const className = toPascalCase(api.name) + 'Client';
  const resources = schema.resources || [];

  let code = `/**
 * ${api.name} SDK - Auto-generated by APIForge
 * Documentation: ${config.seo.siteUrl}/api/${api.slug}/docs
 */

`;

  // Generate interfaces for each resource
  resources.forEach(resource => {
    code += `export interface ${toPascalCase(resource.name)} {\n`;
    code += `  id: string;\n`;
    resource.fields.forEach(field => {
      if (field.name === 'id') return;
      const tsType = mapToTSType(field.type);
      code += `  ${field.name}${field.required ? '' : '?'}: ${tsType};\n`;
    });
    code += `  created_at: string;\n  updated_at: string;\n}\n\n`;
  });

  code += `export interface PaginatedResponse<T> {
  data: T[];
  meta: { total: number; page: number; limit: number; pages: number; };
}

export interface APIForgeConfig {
  apiKey: string;
  baseUrl?: string;
  timeout?: number;
}

export class ${className} {
  private apiKey: string;
  private baseUrl: string;
  private timeout: number;

  constructor(config: APIForgeConfig) {
    this.apiKey = config.apiKey;
    this.baseUrl = config.baseUrl || '${baseUrl}';
    this.timeout = config.timeout || 30000;
  }

  private async request<T>(method: string, path: string, data?: any, params?: Record<string, any>): Promise<T> {
    const url = new URL(\`\${this.baseUrl}\${path}\`);
    if (params) Object.entries(params).forEach(([k, v]) => v != null && url.searchParams.set(k, String(v)));

    const res = await fetch(url.toString(), {
      method,
      headers: { 'X-API-Key': this.apiKey, 'Content-Type': 'application/json' },
      ...(data && { body: JSON.stringify(data) }),
    });

    if (!res.ok) throw new Error(\`[\${res.status}] \${(await res.json().catch(() => ({}))).message || 'Failed'}\`);
    return res.json();
  }

`;

  resources.forEach(resource => {
    const name = resource.name;
    const lower = name.toLowerCase();
    const plural = lower.endsWith('s') ? lower : `${lower}s`;
    const type = toPascalCase(name);

    code += `  list${toPascalCase(plural)}(params?: { page?: number; limit?: number }): Promise<PaginatedResponse<${type}>> {
    return this.request('GET', '/${plural}', null, params);
  }

  get${type}(id: string): Promise<{ data: ${type} }> {
    return this.request('GET', \`/${plural}/\${id}\`);
  }

  create${type}(data: Omit<${type}, 'id' | 'created_at' | 'updated_at'>): Promise<{ data: ${type} }> {
    return this.request('POST', '/${plural}', data);
  }

  update${type}(id: string, data: Partial<${type}>): Promise<{ data: ${type} }> {
    return this.request('PUT', \`/${plural}/\${id}\`, data);
  }

  delete${type}(id: string): Promise<{ message: string }> {
    return this.request('DELETE', \`/${plural}/\${id}\`);
  }

`;
  });

  code += `}\n\nexport default ${className};\n`;
  return code;
}


/**
 * Generate cURL examples
 */
function generateCurlExamples(api, schema, baseUrl) {
  const resources = schema.resources || [];
  let code = `# ${api.name} API - cURL Examples\n# Auto-generated by APIForge\n# Base URL: ${baseUrl}\n\n`;

  resources.forEach(resource => {
    const name = resource.name.toLowerCase();
    const plural = name.endsWith('s') ? name : `${name}s`;

    code += `# === ${resource.name} ===\n\n`;
    code += `# List all ${plural}\n`;
    code += `curl -X GET "${baseUrl}/${plural}" \\\n  -H "X-API-Key: YOUR_API_KEY"\n\n`;
    code += `# Get single ${name}\n`;
    code += `curl -X GET "${baseUrl}/${plural}/ITEM_ID" \\\n  -H "X-API-Key: YOUR_API_KEY"\n\n`;
    code += `# Create ${name}\n`;
    code += `curl -X POST "${baseUrl}/${plural}" \\\n  -H "X-API-Key: YOUR_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '${buildExampleBody(resource.fields)}'\n\n`;
    code += `# Update ${name}\n`;
    code += `curl -X PUT "${baseUrl}/${plural}/ITEM_ID" \\\n  -H "X-API-Key: YOUR_API_KEY" \\\n  -H "Content-Type: application/json" \\\n  -d '${buildExampleBody(resource.fields)}'\n\n`;
    code += `# Delete ${name}\n`;
    code += `curl -X DELETE "${baseUrl}/${plural}/ITEM_ID" \\\n  -H "X-API-Key: YOUR_API_KEY"\n\n`;
  });

  return code;
}

/**
 * Get installation instructions for each language
 */
function getInstallInstructions(language, api) {
  const slug = api.slug;
  const instructions = {
    javascript: {
      install: `npm install @apiforge/${slug}-sdk`,
      usage: `import Client from '@apiforge/${slug}-sdk';\nconst client = new Client('YOUR_API_KEY');`,
    },
    typescript: {
      install: `npm install @apiforge/${slug}-sdk`,
      usage: `import Client from '@apiforge/${slug}-sdk';\nconst client = new Client({ apiKey: 'YOUR_API_KEY' });`,
    },
    python: {
      install: `pip install apiforge-${slug}`,
      usage: `from apiforge_${slug.replace(/-/g, '_')} import Client\nclient = Client('YOUR_API_KEY')`,
    },
    curl: {
      install: 'No installation needed - use cURL directly',
      usage: `curl -H "X-API-Key: YOUR_API_KEY" ${config.baseUrl}/api/v1/live/${slug}`,
    },
  };

  return instructions[language] || instructions.curl;
}

/**
 * Build example JSON body from fields
 */
function buildExampleBody(fields) {
  const body = {};
  fields.forEach(field => {
    if (field.name === 'id') return;
    const examples = {
      string: field.example || 'example_value',
      number: 42,
      integer: 1,
      boolean: true,
      email: 'user@example.com',
      url: 'https://example.com',
      date: '2024-01-01',
      array: [],
      object: {},
    };
    body[field.name] = examples[field.type] || 'value';
  });
  return JSON.stringify(body);
}

/**
 * Convert string to PascalCase
 */
function toPascalCase(str) {
  return str.replace(/[-_\s]+(.)?/g, (_, c) => c ? c.toUpperCase() : '')
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

/**
 * Map schema types to TypeScript types
 */
function mapToTSType(type) {
  const map = {
    string: 'string', number: 'number', integer: 'number',
    boolean: 'boolean', array: 'any[]', object: 'Record<string, any>',
    date: 'string', email: 'string', url: 'string', uuid: 'string',
  };
  return map[type] || 'any';
}

/**
 * Get all available SDK languages
 */
export function getAvailableLanguages() {
  return ['javascript', 'typescript', 'python', 'curl'];
}
